### ISSUE TITLE
It asks for Google Admob initialization 

### ISSUE THREAD

**Issue by cyberlord-007** [vegidio-flutter/appodeal#17]
This is the error I am getting-

The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(17240): * should follow the instructions here:                                       *
E/AndroidRuntime(17240): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(17240): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(17240): * Google Ad Manager publishers should follow instructions here:              *        
E/AndroidRuntime(17240): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.

**Comment by vegidio** [comment]
Since Appodeal also uses AdMob as one of the possible ad networks, you can either add an AdMob Id, if you have one or simply ad a fake one. Follow the instructions in the link provided in your app log.
