### ISSUE TITLE
(iOS) Error occurred while serializing synchronisation response

### ISSUE THREAD

**Issue by branster5** [vegidio-flutter/appodeal#23]
Upon call of Appodeal.shouldShowConsent(); the app crashes with the message:

Unsupported value: Error Domain=com.stack.consentmanager.error Code=1 "Error occurred while serializing synchronisation response" UserInfo={NSLocalizedDescription=Error occurred while serializing synchronisation response} of type NSError
*** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:330
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x185300878 0x199856c50 0x185206000 0x18659791c 0x10833b790 0x10833872c 0x10536cd24 0x105379134 0x1046ab67c 0x184ef324c 0x184ef4db0 0x184f027ac 0x18527c11c 0x185276120 0x18527521c 0x19c2f4784 0x187cae200 0x187cb3a74 0x104600be0 0x184f356c0)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b21ff414 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b21ff414 <+8>:  b.lo   0x1b21ff434               ; <+40>
    0x1b21ff418 <+12>: pacibsp 
    0x1b21ff41c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b21ff420 <+20>: mov    x29, sp
Target 0: (Runner) stopped.

**Comment by houdayec** [comment]
I am getting the same error. Did you find a solution @branster5?

**Comment by branster5** [comment]
@vegidio @houdayec Thanks alot vegidio, Have it working on one app with the dependencies: 
  flutter_tts: ^1.3.0
  speech_to_text: ^4.0.0-nullsafety
  shared_preferences: ^2.0.5
  flutter:
    sdk: flutter
  firebase_ml_vision: ^0.11.0
  camera: ^0.8.0
  image_picker: ^0.7.3
  image_cropper: ^1.3.1
  flutter_image_compress: ^0.7.0
  flutter_statusbarcolor: ^0.2.3
  appodeal_flutter: ^0.5.1
  firebase_core: ^1.0.1

Then in the other app where the problem occurs I have these dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^4.1.0
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.5
  carousel_slider: ^3.0.0
  flutter_swiper: ^1.1.6
  percent_indicator: ^2.1.8
  sqflite: ^2.0.0+3
  http: ^0.13.1
  intl: ^0.17.0
  firebase_core: ^1.0.2
  firebase_database: ^6.1.0
  url_launcher: ^6.0.2
  path_provider: ^2.0.1
  appodeal_flutter: ^0.5.3

It may not be related to that, just trying to help how I can, the sdk on both is sdk: ">=2.7.0 <3.0.0" in the pubspec.yaml.

**Comment by houdayec** [comment]
Getting same error using a brand new ios project with this dependency:

```
appodeal_flutter:
    git:
      url: https://github.com/vegidio-flutter/appodeal
```

Error:

`Unsupported value: Error Domain=com.stack.consentmanager.error Code=1 "Error occurred while serializing synchronisation response" UserInfo={NSLocalizedDescription=Error occurred while serializing synchronisation response} of type NSError`

**Comment by houdayec** [comment]
@branster5 @vegidio I found the problem. My Appodeal iOS key was not matching with my iOS App Bundle Identifier.

I have multiple keys, I was using the one for my dev iOS App.

Go to your Appodeal dashboard, make sure your Appodeal Key and Bundle Identifier are matching.

**Comment by vegidio** [comment]
Good, I'm glad that you found the problem.

@branster5 Did this solve the problem for you as well?

**Comment by vegidio** [comment]
Since there's no response I'm assuming it's fixed for you too.

**Comment by branster5** [comment]
@vegidio Sorry for the late reply, been away over the easter weekend, seems that my project that didn't have appodeal_flutter functioning now works! Thanks alot!
