### ISSUE TITLE
Null-safety support?

### ISSUE THREAD

**Issue by whiplashoo** [vegidio-flutter/appodeal#31]
Is there a plan for adding [null-safety](https://flutter.dev/docs/null-safety) support for this?

**Comment by johnmollaghan** [comment]
Firstly, thanks for such a great plugin, but I agree with @whiplashoo , a null safety version would be great to have, at the moment this is the only plugin preventing me from upgrading to Flutter 2.2.
Also, it would be great to bump to the latest version of the Appodeal libraries etc. Thanks again.

**Comment by vegidio** [comment]
Support for null-safety is available now in version 1.0.0
