### ISSUE TITLE
[Feature request] MREC support

### ISSUE THREAD

**Issue by asduhauisdhbcuasudhu** [vegidio-flutter/appodeal#34]
I'd love to see MREC ads supported.
Sadly, I'm not experienced enough to implement it myself.
Any help?

**Comment by eliabieri** [comment]
Will likely be introduced by #35

**Comment by vegidio** [comment]
Version 1.1.0 is published in pub.dev with support for MREC ads. You can thank @eliabieri for the contribution 💯
