### ISSUE TITLE
 Platform exception in Android Tv

### ISSUE THREAD

**Issue by jpolstre** [vegidio-flutter/appodeal#39]
I'm using your plugin and it's great, it works on a mobile phone; but in the android tv emulator and in android tv I have a platform exception, I wonder if it is your plugin or the appodeal sdk, or maybe it is the activity configured in AndroidManifest.xml: <category android: name = "android.intent.category. LEANBACK_LAUNCHER "/>. The following is the exception I get:

W/System.err( 4812): javax.net.ssl.SSLHandshakeException: Chain validation failed
W/System.err( 4812): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
W/System.err( 4812): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
W/System.err( 4812): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
W/System.err( 4812): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
W/System.err( 4812): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
W/System.err( 4812): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
W/System.err( 4812): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
W/System.err( 4812): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
W/System.err( 4812): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
W/System.err( 4812): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
W/System.err( 4812): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
W/System.err( 4812): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
W/System.err( 4812): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
W/System.err( 4812): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
W/System.err( 4812): 	at com.explorestack.consent.task.b.a(Unknown Source:58)
W/System.err( 4812): 	at com.explorestack.consent.task.b.doInBackground(Unknown Source:0)
W/System.err( 4812): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err( 4812): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 4812): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err( 4812): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 4812): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 4812): 	at java.lang.Thread.run(Thread.java:764)
Caused by: java.security.cert.CertificateException: Chain validation failed
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:707)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:628)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
W/System.err( 4812): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
W/System.err( 4812): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
W/System.err( 4812): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
W/System.err( 4812): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
W/System.err( 4812): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err( 4812): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
W/System.err( 4812): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
W/System.err( 4812): 	... 21 more
W/System.err( 4812): Caused by: java.security.cert.CertPathValidatorException: Responder's certificate not within the validity period
W/System.err( 4812): 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
W/System.err( 4812): 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
W/System.err( 4812): 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
W/System.err( 4812): 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
W/System.err( 4812): 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
W/System.err( 4812): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:703)
W/System.err( 4812): 	... 35 more
W/System.err( 4812): Caused by: java.security.cert.CertificateNotYetValidException: NotBefore: Wed Sep 01 07:00:00 GMT 2021
W/System.err( 4812): 	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:270)
W/System.err( 4812): 	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:646)
W/System.err( 4812): 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:526)
W/System.err( 4812): 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
W/System.err( 4812): 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
W/System.err( 4812): 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
W/System.err( 4812): 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
W/System.err( 4812): 	... 40 more
D/Consent Manager [IO]( 4812): Network Error: javax.net.ssl.SSLHandshakeException: Chain validation failed(com.android.okhttp.internal.huc.HttpURLConnectionImpl:https://a.appbaqend.com/consent/check)
I/flutter ( 4812): PlatformException(CONSENT_INFO_ERROR, Consent Manager Internal Error - javax.net.ssl.SSLHandshakeException: Chain validation failed, null, null)

**Comment by vegidio** [comment]
Looking at the error stack alone it seems to be a problem with the SSL handshake and not something related specifically to Appodeal or this plugin.

In my experience the most common reasons for SSL handshake is the wrong date on the device or lack of internet connectivity. Please check that first.
