### ISSUE TITLE
Missing 'package' key attribute on element package

### ISSUE THREAD

**Issue by Yousry2** [vegidio-flutter/appodeal#8]
Hello, 

Tried to add flutter_appodeal library to my existing app, I encounter the following error message 
Note : I have changed the minSdkVersion in build.grade to "21" in order to avoid multidex  configuration
Any help will be very appreciated

Error :

[com.my.target:mytarget-sdk:5.11.0] C:\Users\Mohamed Yousry\.gradle\caches\transforms-2\files-2.1\3d884126a7f292533bb9e92e8f0b04cc\mytarget-sdk-5.11.0\AndroidManifest.xml:15:9-54 Error:
	Missing 'package' key attribute on element package at [com.my.target:mytarget-sdk:5.11.0] AndroidManifest.xml:15:9-54
[com.my.target:mytarget-sdk:5.11.0] C:\Users\Mohamed Yousry\.gradle\caches\transforms-2\files-2.1\3d884126a7f292533bb9e92e8f0b04cc\mytarget-sdk-5.11.0\AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by Samarkhand** [comment]
same problem

**Comment by vegidio** [comment]
Guys, thanks for reporting the problem, but I don't have much time to dedicate myself to this project right now since my full time job is taking most of my time.

But I will try to look into this and other issues over in a few weeks. Meanwhile, you or anybody else reading this issue is welcomed to open a PR and contribute :)

**Comment by luix93** [comment]
Any idea when this will be fixed?

**Comment by alexandr-efimov** [comment]
Any updates? This package is not usable now with

`[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H114 x86_64, locale ru-UA)
    • Flutter version 1.23.0-18.1.pre at ---
    • Framework revision 198df796aa (3 months ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)
`

**Comment by vegidio** [comment]
Guys, can you please help me debug this issue? It seems to be related to the new package visibility on Android 11 (https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html).

However, if you followed this plugin [installation instructions](https://github.com/vegidio-flutter/appodeal#extra-steps-for-android-only), more specifically the part "Extra steps for Android only", item 5, this shouldn't be a problem:

> 5. Your Android project must use Gradle 4.0.1 or greater. If you are using an older version, please upgrade it by editing the file android/build.gradle.

So please, try this:

1. Upgrade Gradle to at least version 4.0.1 in your project if you haven't done that yet and see if you can use this plugin now.
2. Clone this repository and try to compile and run the same app in the folder `example`.

Let me know your findings and I will continue the investigation from there.

Thanks!

**Comment by vegidio** [comment]
Since there's no response I'm assuming that my comment above reminding about step 5 in the installation process solved the issue that everybody was having? 🤔

In any case, if there's no update until next Saturday I will close this issue. 🔨👷🏾‍♂️

**Comment by luix93** [comment]
Sorry i haven't tried, built my own custom waterfall meanwhile..

**Comment by vegidio** [comment]
I'm assuming this non-issue. If anyone still has this issue, please try what I suggested [above](https://github.com/vegidio-flutter/appodeal/issues/8#issuecomment-761519611) first and let me know before re-open it.
